[package]
publish = false
name = "ruby-wasi"
version.workspace = true
description = "WebAssembly support for Rusty Ruby"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage = "https://github.com/nyar-vm/rusty-ruby"
repository = "https://github.com/nyar-vm/rusty-ruby"
readme = "readme.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ruby = { workspace = true }
ruby-types = { workspace = true }
ruby-ir = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }


