[workspace]
resolver = "3"
members = [
    "compilers/*",
]
default-members = [
    "compilers/*",
]


[workspace.package]
version = "0.0.2"
edition = "2024"
authors = ["RBQ Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nyar-vm/rusty-ruby"

[workspace.dependencies]
async-stream = "0.3"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros", "net", "time", "sync", "io-util", "io-std"] }
async-trait = { version = "0.1" }
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
futures = "0.3"
itertools = "0.14.0"
clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"
# 为 TUI 生成美观表格
comfy-table = "7.1"
# toml = "0.9.11+spec-1.1.0" # replaced by oak-toml
# toml_edit = "0.24.0+spec-1.1.0" # replaced by oak-toml
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1.0"
bytes = "1.5"
byteorder = "1.5"
libloading = "0.8.1"
cranelift = "0.103.0"
cranelift-codegen = "0.103.0"
cranelift-frontend = "0.103.0"
cranelift-module = "0.103.0"
cranelift-jit = "0.103.0"

# Oak parsers
oak-lsp = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-core = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-vfs = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-mcp = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-json = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-toml = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }
oak-ruby = { git = "https://github.com/ygg-lang/oaks.git", branch = "dev", version = "0.0.10" }

# Rusty Ruby crates
ruby-types = { path = "compilers/ruby-types" , version = "0.0.2" }
ruby-ir = { path = "compilers/ruby-ir" , version = "0.0.2" }
ruby = { path = "compilers/ruby" , version = "0.0.2" }

# Macro dependencies
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

# WASM dependencies
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
