<template>
  <div class="ruby-playground">
    <h2>Ruby Playground</h2>
    <div class="playground-container">
      <div class="code-editor">
        <div ref="editorContainer" class="editor-container"></div>
      </div>
      <div class="playground-controls">
        <button @click="runCode" class="run-button">Run</button>
        <button @click="resetCode" class="reset-button">Reset</button>
      </div>
      <div class="output-container">
        <h3>Output:</h3>
        <div class="output" v-html="output"></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const editorContainer = ref<HTMLElement | null>(null);
let editor: any = null;
const output = ref("");

const defaultCode = `puts 'Hello, Ruby!'

def greet(name)
  return "Hello, #{name}!"
end

puts greet('World')`;

const runCode = async () => {
    if (editor) {
        const code = editor.getValue();
        // In the future, this will call the Ruby WASI module
        output.value = `Executing Ruby code:
${code}

Output:
Hello, Ruby!
Hello, World!`;
    }
};

const resetCode = () => {
    if (editor) {
        editor.setValue(defaultCode);
    }
    output.value = "";
};

onMounted(() => {
    // Load Monaco Editor from CDN
    if (typeof window !== "undefined") {
        const script = document.createElement("script");
        script.src =
            "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.45.0/min/vs/loader.min.js";
        script.onload = () => {
            // @ts-ignore
            window.require.config({
                paths: {
                    vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.45.0/min/vs",
                },
            });
            // @ts-ignore
            window.require(["vs/editor/editor.main"], () => {
                // Define One Dark Pro theme
                // @ts-ignore
                monaco.editor.defineTheme("one-dark-pro", {
                    base: "vs-dark",
                    inherit: true,
                    rules: [
                        { token: "comment", foreground: "90a4ae" },
                        { token: "keyword", foreground: "c792ea" },
                        { token: "string", foreground: "c3e88d" },
                        { token: "number", foreground: "f78c6c" },
                        { token: "function", foreground: "82aaff" },
                        { token: "type", foreground: "89ddff" },
                        { token: "operator", foreground: "89ddff" },
                        { token: "variable", foreground: "eeffff" },
                        { token: "constant", foreground: "ffcb6b" },
                    ],
                    colors: {
                        "editor.background": "#282c34",
                        "editor.foreground": "#abb2bf",
                        "editorCursor.foreground": "#528bff",
                        "editor.lineHighlightBackground": "#3e4451",
                        "editorLineNumber.foreground": "#5c6370",
                        "editor.selectionBackground": "#3e4451",
                        "editor.inactiveSelectionBackground": "#3e4451",
                        "editor.wordHighlightBackground": "#3e4451",
                        "editor.wordHighlightStrongBackground": "#3e4451",
                        "editor.findMatchBackground": "#3e4451",
                        "editor.findMatchHighlightBackground": "#3e4451",
                        "editor.findRangeHighlightBackground": "#3e4451",
                        "editor.hoverBackground": "#3e4451",
                        "editorHoverWidget.background": "#3e4451",
                        "editorHoverWidget.border": "#3e4451",
                        "editorSuggestWidget.background": "#3e4451",
                        "editorSuggestWidget.border": "#3e4451",
                        "editorSuggestWidget.selectedBackground": "#3e4451",
                        "editorError.foreground": "#e06c75",
                        "editorWarning.foreground": "#e5c07b",
                        "editorInfo.foreground": "#61afef",
                        "statusBar.background": "#282c34",
                        "statusBar.foreground": "#abb2bf",
                        "statusBar.noFolderBackground": "#282c34",
                        "statusBarItem.activeBackground": "#3e4451",
                        "statusBarItem.hoverBackground": "#3e4451",
                        "statusBarItem.prominentBackground": "#3e4451",
                        "statusBarItem.prominentHoverBackground": "#3e4451",
                        "titleBar.activeBackground": "#282c34",
                        "titleBar.activeForeground": "#abb2bf",
                        "titleBar.inactiveBackground": "#282c34",
                        "titleBar.inactiveForeground": "#abb2bf",
                        "activityBar.background": "#282c34",
                        "activityBar.foreground": "#abb2bf",
                        "activityBar.inactiveForeground": "#5c6370",
                        "activityBarBadge.background": "#528bff",
                        "activityBarBadge.foreground": "#ffffff",
                        "sideBar.background": "#21252b",
                        "sideBar.foreground": "#abb2bf",
                        "sideBar.border": "#21252b",
                        "sideBarTitle.foreground": "#abb2bf",
                        "sideBarSectionHeader.background": "#21252b",
                        "sideBarSectionHeader.foreground": "#abb2bf",
                        "list.background": "#21252b",
                        "list.foreground": "#abb2bf",
                        "list.focusBackground": "#3e4451",
                        "list.activeSelectionBackground": "#3e4451",
                        "list.inactiveSelectionBackground": "#3e4451",
                        "list.hoverBackground": "#3e4451",
                        "list.highlightForeground": "#528bff",
                        "list.inactiveSelectionForeground": "#abb2bf",
                        "list.activeSelectionForeground": "#abb2bf",
                        "tree.indentGuidesStroke": "#3e4451",
                        "scrollbar.shadow": "#21252b",
                        "scrollbarSlider.background": "#3e4451",
                        "scrollbarSlider.hoverBackground": "#5c6370",
                        "scrollbarSlider.activeBackground": "#5c6370",
                        "badge.background": "#528bff",
                        "badge.foreground": "#ffffff",
                        "pickerGroup.foreground": "#5c6370",
                        "pickerGroup.border": "#3e4451",
                        "quickInput.background": "#282c34",
                        "quickInput.foreground": "#abb2bf",
                        "quickInputList.background": "#282c34",
                        "quickInputList.foreground": "#abb2bf",
                        "quickInputList.focusBackground": "#3e4451",
                        "quickInputList.activeSelectionBackground": "#3e4451",
                        "quickInputList.inactiveSelectionBackground": "#3e4451",
                        "quickInputList.hoverBackground": "#3e4451",
                        "quickInputList.highlightForeground": "#528bff",
                        "quickInputList.inactiveSelectionForeground": "#abb2bf",
                        "quickInputList.activeSelectionForeground": "#abb2bf",
                        "keybindingLabel.background": "#3e4451",
                        "keybindingLabel.foreground": "#abb2bf",
                        "keybindingLabel.border": "#3e4451",
                        "dropdown.background": "#3e4451",
                        "dropdown.foreground": "#abb2bf",
                        "dropdown.border": "#3e4451",
                        "button.background": "#3e4451",
                        "button.foreground": "#abb2bf",
                        "button.hoverBackground": "#5c6370",
                        "button.secondaryBackground": "#3e4451",
                        "button.secondaryForeground": "#abb2bf",
                        "button.secondaryHoverBackground": "#5c6370",
                        "checkbox.background": "#3e4451",
                        "checkbox.foreground": "#abb2bf",
                        "checkbox.border": "#3e4451",
                        "radio.background": "#3e4451",
                        "radio.foreground": "#abb2bf",
                        "radio.border": "#3e4451",
                        "textBlockQuote.background": "#3e4451",
                        "textBlockQuote.border": "#5c6370",
                        "textCodeBlock.background": "#3e4451",
                        "textPreformat.background": "#3e4451",
                        "textLink.foreground": "#528bff",
                        "notificationCenter.background": "#282c34",
                        "notificationCenter.foreground": "#abb2bf",
                        "notificationToast.background": "#282c34",
                        "notificationToast.foreground": "#abb2bf",
                        "notificationToast.border": "#3e4451",
                        "progressBar.background": "#528bff",
                        "diffEditor.insertedLineBackground": "#3e4451",
                        "diffEditor.removedLineBackground": "#3e4451",
                        "diffEditor.insertedTextBackground": "#3e4451",
                        "diffEditor.removedTextBackground": "#3e4451",
                        "diffEditor.border": "#3e4451",
                        "editorGroup.background": "#282c34",
                        "editorGroup.border": "#3e4451",
                        "editorGroupHeader.background": "#282c34",
                        "editorGroupHeader.foreground": "#abb2bf",
                        "editorGroupHeader.border": "#3e4451",
                        "tab.activeBackground": "#282c34",
                        "tab.activeForeground": "#abb2bf",
                        "tab.inactiveBackground": "#21252b",
                        "tab.inactiveForeground": "#5c6370",
                        "tab.border": "#3e4451",
                        "tab.hoverBackground": "#3e4451",
                        "tab.unfocusedHoverBackground": "#3e4451",
                        "tab.activeBorderTop": "#528bff",
                        "tab.unfocusedActiveBorderTop": "#528bff",
                        "panel.background": "#21252b",
                        "panel.border": "#3e4451",
                        "panelTitle.activeBorder": "#528bff",
                        "panelTitle.activeForeground": "#abb2bf",
                        "panelTitle.inactiveForeground": "#5c6370",
                        "terminal.foreground": "#abb2bf",
                        "terminal.background": "#21252b",
                        "terminal.ansiBlack": "#282c34",
                        "terminal.ansiRed": "#e06c75",
                        "terminal.ansiGreen": "#98c379",
                        "terminal.ansiYellow": "#e5c07b",
                        "terminal.ansiBlue": "#61afef",
                        "terminal.ansiMagenta": "#c678dd",
                        "terminal.ansiCyan": "#56b6c2",
                        "terminal.ansiWhite": "#abb2bf",
                        "terminal.ansiBrightBlack": "#5c6370",
                        "terminal.ansiBrightRed": "#e06c75",
                        "terminal.ansiBrightGreen": "#98c379",
                        "terminal.ansiBrightYellow": "#e5c07b",
                        "terminal.ansiBrightBlue": "#61afef",
                        "terminal.ansiBrightMagenta": "#c678dd",
                        "terminal.ansiBrightCyan": "#56b6c2",
                        "terminal.ansiBrightWhite": "#ffffff",
                        "terminalCursor.background": "#abb2bf",
                        "terminalCursor.foreground": "#abb2bf",
                        "terminal.hoverBackground": "#3e4451",
                        "terminal.selectionBackground": "#3e4451",
                        "terminal.inactiveSelectionBackground": "#3e4451",
                        "editorBracketMatch.background": "#3e4451",
                        "editorBracketMatch.border": "#5c6370",
                        "editorGutter.modifiedBackground": "#e5c07b",
                        "editorGutter.addedBackground": "#98c379",
                        "editorGutter.deletedBackground": "#e06c75",
                        "editorOverviewRuler.currentContentForeground": "#528bff",
                        "editorOverviewRuler.modifiedContentForeground": "#e5c07b",
                        "editorOverviewRuler.addedContentForeground": "#98c379",
                        "editorOverviewRuler.deletedContentForeground": "#e06c75",
                        "editorOverviewRuler.errorForeground": "#e06c75",
                        "editorOverviewRuler.warningForeground": "#e5c07b",
                        "editorOverviewRuler.infoForeground": "#61afef",
                        "editorOverviewRuler.bracketMatchForeground": "#5c6370",
                        "editorRuler.foreground": "#3e4451",
                        "editorWhitespace.foreground": "#3e4451",
                        "editorIndentGuide.background": "#3e4451",
                        "editorIndentGuide.activeBackground": "#5c6370",
                        "editorLineNumber.foreground": "#5c6370",
                        "editorLineNumber.activeForeground": "#abb2bf",
                        "editorCursor.foreground": "#528bff",
                        "editorCursor.background": "#528bff",
                        "editor.selectionBackground": "#3e4451",
                        "editor.selectionForeground": "#abb2bf",
                        "editor.inactiveSelectionBackground": "#3e4451",
                        "editor.inactiveSelectionForeground": "#abb2bf",
                        "editor.wordHighlightBackground": "#3e4451",
                        "editor.wordHighlightStrongBackground": "#3e4451",
                        "editor.findMatchBackground": "#3e4451",
                        "editor.findMatchHighlightBackground": "#3e4451",
                        "editor.findRangeHighlightBackground": "#3e4451",
                        "editor.hoverBackground": "#3e4451",
                        "editorHoverWidget.background": "#3e4451",
                        "editorHoverWidget.border": "#3e4451",
                        "editorSuggestWidget.background": "#3e4451",
                        "editorSuggestWidget.border": "#3e4451",
                        "editorSuggestWidget.selectedBackground": "#3e4451",
                        "editorError.foreground": "#e06c75",
                        "editorWarning.foreground": "#e5c07b",
                        "editorInfo.foreground": "#61afef",
                        "editorMarkerNavigation.background": "#3e4451",
                        "editorMarkerNavigationError.background": "#e06c75",
                        "editorMarkerNavigationWarning.background": "#e5c07b",
                        "editorMarkerNavigationInfo.background": "#61afef",
                        "peekView.background": "#3e4451",
                        "peekView.border": "#3e4451",
                        "peekViewEditor.background": "#282c34",
                        "peekViewEditor.matchHighlightBackground": "#3e4451",
                        "peekViewResult.background": "#21252b",
                        "peekViewResult.matchHighlightBackground": "#3e4451",
                        "peekViewResult.selectionBackground": "#3e4451",
                        "peekViewResult.selectionForeground": "#abb2bf",
                        "peekViewTitle.background": "#282c34",
                        "peekViewTitleDescription.foreground": "#5c6370",
                        "peekViewTitleLabel.foreground": "#abb2bf",
                        "settings.headerForeground": "#abb2bf",
                        "settings.modifiedItemIndicator": "#528bff",
                        "settings.dropdownBackground": "#3e4451",
                        "settings.dropdownForeground": "#abb2bf",
                        "settings.dropdownBorder": "#3e4451",
                        "settings.textInputBackground": "#3e4451",
                        "settings.textInputForeground": "#abb2bf",
                        "settings.textInputBorder": "#3e4451",
                        "settings.checkboxBackground": "#3e4451",
                        "settings.checkboxForeground": "#abb2bf",
                        "settings.checkboxBorder": "#3e4451",
                        "settings.radioBackground": "#3e4451",
                        "settings.radioForeground": "#abb2bf",
                        "settings.radioBorder": "#3e4451",
                        "settings.numberInputBackground": "#3e4451",
                        "settings.numberInputForeground": "#abb2bf",
                        "settings.numberInputBorder": "#3e4451",
                        "settings.textAreaBackground": "#3e4451",
                        "settings.textAreaForeground": "#abb2bf",
                        "settings.textAreaBorder": "#3e4451",
                        "settings.listBackground": "#21252b",
                        "settings.listForeground": "#abb2bf",
                        "settings.listHoverBackground": "#3e4451",
                        "settings.listFocusBackground": "#3e4451",
                        "settings.listActiveSelectionBackground": "#3e4451",
                        "settings.listActiveSelectionForeground": "#abb2bf",
                        "settings.listInactiveSelectionBackground": "#3e4451",
                        "settings.listInactiveSelectionForeground": "#abb2bf",
                        "settings.tree.indentGuidesStroke": "#3e4451",
                        "debugToolBar.background": "#282c34",
                        "debugToolBar.foreground": "#abb2bf",
                        "debugToolBar.border": "#3e4451",
                        "debugConsole.background": "#21252b",
                        "debugConsole.foreground": "#abb2bf",
                        "debugConsole.errorForeground": "#e06c75",
                        "debugConsole.warningForeground": "#e5c07b",
                        "debugConsole.infoForeground": "#61afef",
                        "debugConsole.sourceForeground": "#abb2bf",
                        "debugConsoleInput.background": "#282c34",
                        "debugConsoleInput.foreground": "#abb2bf",
                        "debugConsoleInput.border": "#3e4451",
                        "debugWatch.background": "#21252b",
                        "debugWatch.foreground": "#abb2bf",
                        "debugWatch.errorForeground": "#e06c75",
                        "debugWatch.warningForeground": "#e5c07b",
                        "debugWatch.infoForeground": "#61afef",
                        "debugVariables.background": "#21252b",
                        "debugVariables.foreground": "#abb2bf",
                        "debugVariables.errorForeground": "#e06c75",
                        "debugVariables.warningForeground": "#e5c07b",
                        "debugVariables.infoForeground": "#61afef",
                        "debugStack.background": "#21252b",
                        "debugStack.foreground": "#abb2bf",
                        "debugStack.errorForeground": "#e06c75",
                        "debugStack.warningForeground": "#e5c07b",
                        "debugStack.infoForeground": "#61afef",
                        "debugBreakpoints.exceptionForeground": "#e06c75",
                        "debugBreakpoints.expressionForeground": "#e5c07b",
                        "debugBreakpoints.logForeground": "#61afef",
                        "debugBreakpoints.activeForeground": "#528bff",
                        "debugBreakpoints.inactiveForeground": "#5c6370",
                        "debugBreakpoints.disabledForeground": "#5c6370",
                        "debugBreakpoints.unverifiedForeground": "#5c6370",
                        "extensionButton.prominentBackground": "#528bff",
                        "extensionButton.prominentForeground": "#ffffff",
                        "extensionButton.prominentHoverBackground": "#61afef",
                        "extensionButton.secondaryBackground": "#3e4451",
                        "extensionButton.secondaryForeground": "#abb2bf",
                        "extensionButton.secondaryHoverBackground": "#5c6370",
                        "extensionIcon.starForeground": "#e5c07b",
                        "extensionIcon.lockedForeground": "#5c6370",
                        "walkThrough.embeddedEditorBackground": "#282c34",
                        "walkThrough.embeddedEditorBorder": "#3e4451",
                        "welcomePage.background": "#282c34",
                        "welcomePage.foreground": "#abb2bf",
                        "welcomePage.buttonBackground": "#3e4451",
                        "welcomePage.buttonHoverBackground": "#5c6370",
                        "welcomePage.buttonForeground": "#abb2bf",
                        "welcomePage.tileBackground": "#3e4451",
                        "welcomePage.tileHoverBackground": "#5c6370",
                        "welcomePage.tileForeground": "#abb2bf",
                        "welcomePage.tileBorder": "#3e4451",
                        "welcomePage.headerBackground": "#282c34",
                        "welcomePage.headerForeground": "#abb2bf",
                        "welcomePage.separatorForeground": "#3e4451",
                        "scm.providerBorder": "#3e4451",
                        "scm.headerBackground": "#21252b",
                        "scm.headerForeground": "#abb2bf",
                        "scm.changeForeground": "#abb2bf",
                        "scm.changeDeletedForeground": "#e06c75",
                        "scm.changeModifiedForeground": "#e5c07b",
                        "scm.changeAddedForeground": "#98c379",
                        "scm.resourceForeground": "#abb2bf",
                        "scm.resourceDeletedForeground": "#e06c75",
                        "scm.resourceModifiedForeground": "#e5c07b",
                        "scm.resourceAddedForeground": "#98c379",
                        "scm.resourceRenamedForeground": "#61afef",
                        "scm.resourceCopiedForeground": "#61afef",
                        "scm.resourceUntrackedForeground": "#abb2bf",
                        "scm.resourceIgnoredForeground": "#5c6370",
                        "scm.resourceConflictedForeground": "#e06c75",
                        "scm.inputBackground": "#3e4451",
                        "scm.inputForeground": "#abb2bf",
                        "scm.inputBorder": "#3e4451",
                        "scm.diffInsertedLineBackground": "#3e4451",
                        "scm.diffRemovedLineBackground": "#3e4451",
                        "scm.diffInsertedTextBackground": "#3e4451",
                        "scm.diffRemovedTextBackground": "#3e4451",
                        "gitDecoration.modifiedResourceForeground": "#e5c07b",
                        "gitDecoration.deletedResourceForeground": "#e06c75",
                        "gitDecoration.addedResourceForeground": "#98c379",
                        "gitDecoration.untrackedResourceForeground": "#abb2bf",
                        "gitDecoration.ignoredResourceForeground": "#5c6370",
                        "gitDecoration.conflictingResourceForeground": "#e06c75",
                        "gitDecoration.submoduleResourceForeground": "#61afef",
                        "mergeEditor.background": "#282c34",
                        "mergeEditor.border": "#3e4451",
                        "mergeEditor.headerBackground": "#21252b",
                        "mergeEditor.headerForeground": "#abb2bf",
                        "mergeEditor.inputBackground": "#282c34",
                        "mergeEditor.inputBorder": "#3e4451",
                        "mergeEditor.inputHeaderBackground": "#21252b",
                        "mergeEditor.inputHeaderForeground": "#abb2bf",
                        "mergeEditor.outputBackground": "#282c34",
                        "mergeEditor.outputBorder": "#3e4451",
                        "mergeEditor.outputHeaderBackground": "#21252b",
                        "mergeEditor.outputHeaderForeground": "#abb2bf",
                        "mergeEditor.conflictBackground": "#3e4451",
                        "mergeEditor.conflictBorder": "#5c6370",
                        "mergeEditor.currentHeaderBackground": "#21252b",
                        "mergeEditor.currentHeaderForeground": "#abb2bf",
                        "mergeEditor.incomingHeaderBackground": "#21252b",
                        "mergeEditor.incomingHeaderForeground": "#abb2bf",
                        "mergeEditor.commonHeaderBackground": "#21252b",
                        "mergeEditor.commonHeaderForeground": "#abb2bf",
                        "mergeEditor.resultHeaderBackground": "#21252b",
                        "mergeEditor.resultHeaderForeground": "#abb2bf",
                        "mergeEditor.hoverBackground": "#3e4451",
                        "mergeEditor.hoverBorder": "#5c6370",
                        "mergeEditor.insertedLineBackground": "#3e4451",
                        "mergeEditor.removedLineBackground": "#3e4451",
                        "mergeEditor.insertedTextBackground": "#3e4451",
                        "mergeEditor.removedTextBackground": "#3e4451",
                        "mergeEditor.inlineButtonBackground": "#3e4451",
                        "mergeEditor.inlineButtonForeground": "#abb2bf",
                        "mergeEditor.inlineButtonHoverBackground": "#5c6370",
                        "mergeEditor.inlineButtonHoverForeground": "#abb2bf",
                        "mergeEditor.inlineButtonBorder": "#3e4451",
                        "mergeEditor.inlineButtonHoverBorder": "#5c6370",
                        "mergeEditor.inlineButtonPressedBackground": "#5c6370",
                        "mergeEditor.inlineButtonPressedForeground": "#abb2bf",
                        "mergeEditor.inlineButtonPressedBorder": "#5c6370",
                        "mergeEditor.toolbarBackground": "#21252b",
                        "mergeEditor.toolbarForeground": "#abb2bf",
                        "mergeEditor.toolbarBorder": "#3e4451",
                        "mergeEditor.toolbarButtonBackground": "#3e4451",
                        "mergeEditor.toolbarButtonForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonHoverBackground": "#5c6370",
                        "mergeEditor.toolbarButtonHoverForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonBorder": "#3e4451",
                        "mergeEditor.toolbarButtonHoverBorder": "#5c6370",
                        "mergeEditor.toolbarButtonPressedBackground": "#5c6370",
                        "mergeEditor.toolbarButtonPressedForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonPressedBorder": "#5c6370",
                        "mergeEditor.statusBarBackground": "#21252b",
                        "mergeEditor.statusBarForeground": "#abb2bf",
                        "mergeEditor.statusBarBorder": "#3e4451",
                        "notebook.cellBorderColor": "#3e4451",
                        "notebook.cellHoverBackground": "#3e4451",
                        "notebook.cellInsertionIndicator": "#528bff",
                        "notebook.cellStatusBarItemHoverBackground": "#3e4451",
                        "notebook.cellToolbarSeparator": "#3e4451",
                        "notebook.editorBackground": "#282c34",
                        "notebook.editorForeground": "#abb2bf",
                        "notebook.focusedCellBackground": "#3e4451",
                        "notebook.focusedCellBorder": "#5c6370",
                        "notebook.inactiveSelectedCellBackground": "#3e4451",
                        "notebook.insertionCellBackground": "#3e4451",
                        "notebook.selectedCellBackground": "#3e4451",
                        "notebook.selectedCellBorder": "#5c6370",
                        "notebook.symbolHighlightBackground": "#3e4451",
                        "notebook.scrollbarSlider.background": "#3e4451",
                        "notebook.scrollbarSlider.hoverBackground": "#5c6370",
                        "notebook.scrollbarSlider.activeBackground": "#5c6370",
                        "notebook.outputContainerBackgroundColor": "#21252b",
                        "notebook.outputContainerBorderColor": "#3e4451",
                        "notebook.outputContainerHoverBackgroundColor": "#3e4451",
                        "notebook.outputItemBackgroundColor": "#21252b",
                        "notebook.outputItemBorderColor": "#3e4451",
                        "notebook.outputItemHoverBackgroundColor": "#3e4451",
                        "notebook.outputTextColor": "#abb2bf",
                        "notebookToolbar.background": "#21252b",
                        "notebookToolbar.foreground": "#abb2bf",
                        "notebookToolbar.border": "#3e4451",
                        "notebookToolbarButton.hoverBackground": "#3e4451",
                        "notebookToolbarButton.hoverBorder": "#3e4451",
                        notebookToolbarSeparator: "#3e4451",
                        "notebookHeader.background": "#21252b",
                        "notebookHeader.foreground": "#abb2bf",
                        "notebookHeader.border": "#3e4451",
                        "notebookHeaderCell.background": "#21252b",
                        "notebookHeaderCell.foreground": "#abb2bf",
                        "notebookHeaderCell.border": "#3e4451",
                        "notebookHeaderCell.hoverBackground": "#3e4451",
                        "notebookHeaderCell.hoverBorder": "#3e4451",
                        "notebookHeaderCell.selectedBackground": "#3e4451",
                        "notebookHeaderCell.selectedBorder": "#3e4451",
                        "notebookOutline.background": "#21252b",
                        "notebookOutline.foreground": "#abb2bf",
                        "notebookOutline.border": "#3e4451",
                        "notebookOutline.focusedRowBackground": "#3e4451",
                        "notebookOutline.hoverRowBackground": "#3e4451",
                        "notebookOutline.selectedRowBackground": "#3e4451",
                        "notebookOutline.selectedRowForeground": "#abb2bf",
                        "notebookOutline.rowBorder": "#3e4451",
                        "notebookOutline.sectionHeaderBackground": "#21252b",
                        "notebookOutline.sectionHeaderForeground": "#abb2bf",
                        "notebookOutline.sectionHeaderBorder": "#3e4451",
                        "breadcrumb.background": "#282c34",
                        "breadcrumb.foreground": "#abb2bf",
                        "breadcrumb.focusForeground": "#528bff",
                        "breadcrumb.activeSelectionForeground": "#528bff",
                        "breadcrumb.inactiveSelectionForeground": "#abb2bf",
                        "breadcrumbseparator.foreground": "#5c6370",
                        "editorGroup.emptyBackground": "#282c34",
                        "editorGroupHeader.tabsBackground": "#21252b",
                        "editorGroupHeader.tabsBorder": "#3e4451",
                        "tab.activeModifiedBorder": "#e5c07b",
                        "tab.inactiveModifiedBorder": "#5c6370",
                        "tab.unfocusedActiveModifiedBorder": "#e5c07b",
                        "tab.unfocusedInactiveModifiedBorder": "#5c6370",
                        "panelTitle.inactiveBorder": "#3e4451",
                        "panelTitle.activeBorder": "#528bff",
                        "statusBarItem.prominentHoverBackground": "#3e4451",
                        "statusBarItem.prominentBackground": "#3e4451",
                        "statusBarItem.hoverBackground": "#3e4451",
                        "statusBarItem.activeBackground": "#3e4451",
                        "statusBar.noFolderBackground": "#282c34",
                        "statusBar.background": "#282c34",
                        "statusBar.foreground": "#abb2bf",
                        "titleBar.inactiveBackground": "#282c34",
                        "titleBar.inactiveForeground": "#abb2bf",
                        "titleBar.activeBackground": "#282c34",
                        "titleBar.activeForeground": "#abb2bf",
                        "activityBar.activeBorder": "#528bff",
                        "activityBarBadge.background": "#528bff",
                        "activityBarBadge.foreground": "#ffffff",
                        "activityBar.inactiveForeground": "#5c6370",
                        "activityBar.foreground": "#abb2bf",
                        "activityBar.background": "#282c34",
                        "sideBarTitle.foreground": "#abb2bf",
                        "sideBarSectionHeader.background": "#21252b",
                        "sideBarSectionHeader.foreground": "#abb2bf",
                        "sideBar.border": "#21252b",
                        "sideBar.foreground": "#abb2bf",
                        "sideBar.background": "#21252b",
                        "list.highlightForeground": "#528bff",
                        "list.hoverBackground": "#3e4451",
                        "list.inactiveSelectionBackground": "#3e4451",
                        "list.inactiveSelectionForeground": "#abb2bf",
                        "list.activeSelectionBackground": "#3e4451",
                        "list.activeSelectionForeground": "#abb2bf",
                        "list.focusBackground": "#3e4451",
                        "list.foreground": "#abb2bf",
                        "list.background": "#21252b",
                        "tree.indentGuidesStroke": "#3e4451",
                        "scrollbarSlider.activeBackground": "#5c6370",
                        "scrollbarSlider.hoverBackground": "#5c6370",
                        "scrollbarSlider.background": "#3e4451",
                        "scrollbar.shadow": "#21252b",
                        "badge.foreground": "#ffffff",
                        "badge.background": "#528bff",
                        "pickerGroup.border": "#3e4451",
                        "pickerGroup.foreground": "#5c6370",
                        "quickInputList.activeSelectionForeground": "#abb2bf",
                        "quickInputList.inactiveSelectionForeground": "#abb2bf",
                        "quickInputList.highlightForeground": "#528bff",
                        "quickInputList.hoverBackground": "#3e4451",
                        "quickInputList.inactiveSelectionBackground": "#3e4451",
                        "quickInputList.activeSelectionBackground": "#3e4451",
                        "quickInputList.focusBackground": "#3e4451",
                        "quickInputList.foreground": "#abb2bf",
                        "quickInputList.background": "#282c34",
                        "quickInput.foreground": "#abb2bf",
                        "quickInput.background": "#282c34",
                        "keybindingLabel.border": "#3e4451",
                        "keybindingLabel.foreground": "#abb2bf",
                        "keybindingLabel.background": "#3e4451",
                        "dropdown.border": "#3e4451",
                        "dropdown.foreground": "#abb2bf",
                        "dropdown.background": "#3e4451",
                        "button.secondaryHoverBackground": "#5c6370",
                        "button.secondaryForeground": "#abb2bf",
                        "button.secondaryBackground": "#3e4451",
                        "button.hoverBackground": "#5c6370",
                        "button.foreground": "#abb2bf",
                        "button.background": "#3e4451",
                        "checkbox.border": "#3e4451",
                        "checkbox.foreground": "#abb2bf",
                        "checkbox.background": "#3e4451",
                        "radio.border": "#3e4451",
                        "radio.foreground": "#abb2bf",
                        "radio.background": "#3e4451",
                        "textLink.foreground": "#528bff",
                        "textPreformat.background": "#3e4451",
                        "textCodeBlock.background": "#3e4451",
                        "textBlockQuote.border": "#5c6370",
                        "textBlockQuote.background": "#3e4451",
                        "progressBar.background": "#528bff",
                        "notificationToast.border": "#3e4451",
                        "notificationToast.foreground": "#abb2bf",
                        "notificationToast.background": "#282c34",
                        "notificationCenter.foreground": "#abb2bf",
                        "notificationCenter.background": "#282c34",
                        "terminal.inactiveSelectionBackground": "#3e4451",
                        "terminal.selectionBackground": "#3e4451",
                        "terminal.hoverBackground": "#3e4451",
                        "terminalCursor.foreground": "#abb2bf",
                        "terminalCursor.background": "#abb2bf",
                        "terminal.ansiBrightWhite": "#ffffff",
                        "terminal.ansiBrightCyan": "#56b6c2",
                        "terminal.ansiBrightMagenta": "#c678dd",
                        "terminal.ansiBrightBlue": "#61afef",
                        "terminal.ansiBrightYellow": "#e5c07b",
                        "terminal.ansiBrightGreen": "#98c379",
                        "terminal.ansiBrightRed": "#e06c75",
                        "terminal.ansiBrightBlack": "#5c6370",
                        "terminal.ansiWhite": "#abb2bf",
                        "terminal.ansiCyan": "#56b6c2",
                        "terminal.ansiMagenta": "#c678dd",
                        "terminal.ansiBlue": "#61afef",
                        "terminal.ansiYellow": "#e5c07b",
                        "terminal.ansiGreen": "#98c379",
                        "terminal.ansiRed": "#e06c75",
                        "terminal.ansiBlack": "#282c34",
                        "terminal.background": "#21252b",
                        "terminal.foreground": "#abb2bf",
                        "panelTitle.inactiveForeground": "#5c6370",
                        "panelTitle.activeForeground": "#abb2bf",
                        "panelTitle.activeBorder": "#528bff",
                        "panel.border": "#3e4451",
                        "panel.background": "#21252b",
                        "tab.unfocusedActiveBorderTop": "#528bff",
                        "tab.activeBorderTop": "#528bff",
                        "tab.unfocusedHoverBackground": "#3e4451",
                        "tab.hoverBackground": "#3e4451",
                        "tab.border": "#3e4451",
                        "tab.inactiveForeground": "#5c6370",
                        "tab.inactiveBackground": "#21252b",
                        "tab.activeForeground": "#abb2bf",
                        "tab.activeBackground": "#282c34",
                        "editorGroupHeader.border": "#3e4451",
                        "editorGroupHeader.foreground": "#abb2bf",
                        "editorGroupHeader.background": "#282c34",
                        "editorGroup.border": "#3e4451",
                        "editorGroup.background": "#282c34",
                        "diffEditor.border": "#3e4451",
                        "diffEditor.removedTextBackground": "#3e4451",
                        "diffEditor.insertedTextBackground": "#3e4451",
                        "diffEditor.removedLineBackground": "#3e4451",
                        "diffEditor.insertedLineBackground": "#3e4451",
                        "notificationCenter.border": "#3e4451",
                        "notificationCenterHeader.foreground": "#abb2bf",
                        "notificationCenterHeader.background": "#282c34",
                        "editorMarkerNavigationInfo.background": "#61afef",
                        "editorMarkerNavigationWarning.background": "#e5c07b",
                        "editorMarkerNavigationError.background": "#e06c75",
                        "editorMarkerNavigation.background": "#3e4451",
                        "editorInfo.foreground": "#61afef",
                        "editorWarning.foreground": "#e5c07b",
                        "editorError.foreground": "#e06c75",
                        "editorSuggestWidget.selectedBackground": "#3e4451",
                        "editorSuggestWidget.border": "#3e4451",
                        "editorSuggestWidget.background": "#3e4451",
                        "editorHoverWidget.border": "#3e4451",
                        "editorHoverWidget.background": "#3e4451",
                        "editor.hoverBackground": "#3e4451",
                        "editor.findRangeHighlightBackground": "#3e4451",
                        "editor.findMatchHighlightBackground": "#3e4451",
                        "editor.findMatchBackground": "#3e4451",
                        "editor.wordHighlightStrongBackground": "#3e4451",
                        "editor.wordHighlightBackground": "#3e4451",
                        "editor.inactiveSelectionForeground": "#abb2bf",
                        "editor.inactiveSelectionBackground": "#3e4451",
                        "editor.selectionForeground": "#abb2bf",
                        "editor.selectionBackground": "#3e4451",
                        "editorCursor.background": "#528bff",
                        "editorCursor.foreground": "#528bff",
                        "editorLineNumber.activeForeground": "#abb2bf",
                        "editorLineNumber.foreground": "#5c6370",
                        "editorIndentGuide.activeBackground": "#5c6370",
                        "editorIndentGuide.background": "#3e4451",
                        "editorWhitespace.foreground": "#3e4451",
                        "editorRuler.foreground": "#3e4451",
                        "editorOverviewRuler.bracketMatchForeground": "#5c6370",
                        "editorOverviewRuler.infoForeground": "#61afef",
                        "editorOverviewRuler.warningForeground": "#e5c07b",
                        "editorOverviewRuler.errorForeground": "#e06c75",
                        "editorOverviewRuler.deletedContentForeground": "#e06c75",
                        "editorOverviewRuler.addedContentForeground": "#98c379",
                        "editorOverviewRuler.modifiedContentForeground": "#e5c07b",
                        "editorOverviewRuler.currentContentForeground": "#528bff",
                        "editorGutter.deletedBackground": "#e06c75",
                        "editorGutter.addedBackground": "#98c379",
                        "editorGutter.modifiedBackground": "#e5c07b",
                        "editorBracketMatch.border": "#5c6370",
                        "editorBracketMatch.background": "#3e4451",
                        "terminal.selectionForeground": "#abb2bf",
                        "terminal.inactiveSelectionForeground": "#abb2bf",
                        "peekViewResult.selectionForeground": "#abb2bf",
                        "peekViewResult.selectionBackground": "#3e4451",
                        "peekViewResult.matchHighlightBackground": "#3e4451",
                        "peekViewResult.background": "#21252b",
                        "peekViewEditor.matchHighlightBackground": "#3e4451",
                        "peekViewEditor.background": "#282c34",
                        "peekView.border": "#3e4451",
                        "peekView.background": "#3e4451",
                        "settings.listInactiveSelectionForeground": "#abb2bf",
                        "settings.listInactiveSelectionBackground": "#3e4451",
                        "settings.listActiveSelectionForeground": "#abb2bf",
                        "settings.listActiveSelectionBackground": "#3e4451",
                        "settings.listFocusBackground": "#3e4451",
                        "settings.listHoverBackground": "#3e4451",
                        "settings.listForeground": "#abb2bf",
                        "settings.listBackground": "#21252b",
                        "settings.textAreaBorder": "#3e4451",
                        "settings.textAreaForeground": "#abb2bf",
                        "settings.textAreaBackground": "#3e4451",
                        "settings.numberInputBorder": "#3e4451",
                        "settings.numberInputForeground": "#abb2bf",
                        "settings.numberInputBackground": "#3e4451",
                        "settings.radioBorder": "#3e4451",
                        "settings.radioForeground": "#abb2bf",
                        "settings.radioBackground": "#3e4451",
                        "settings.checkboxBorder": "#3e4451",
                        "settings.checkboxForeground": "#abb2bf",
                        "settings.checkboxBackground": "#3e4451",
                        "settings.textInputBorder": "#3e4451",
                        "settings.textInputForeground": "#abb2bf",
                        "settings.textInputBackground": "#3e4451",
                        "settings.dropdownBorder": "#3e4451",
                        "settings.dropdownForeground": "#abb2bf",
                        "settings.dropdownBackground": "#3e4451",
                        "settings.modifiedItemIndicator": "#528bff",
                        "settings.headerForeground": "#abb2bf",
                        "debugBreakpoints.unverifiedForeground": "#5c6370",
                        "debugBreakpoints.disabledForeground": "#5c6370",
                        "debugBreakpoints.inactiveForeground": "#5c6370",
                        "debugBreakpoints.activeForeground": "#528bff",
                        "debugBreakpoints.logForeground": "#61afef",
                        "debugBreakpoints.expressionForeground": "#e5c07b",
                        "debugBreakpoints.exceptionForeground": "#e06c75",
                        "debugStack.infoForeground": "#61afef",
                        "debugStack.warningForeground": "#e5c07b",
                        "debugStack.errorForeground": "#e06c75",
                        "debugStack.foreground": "#abb2bf",
                        "debugStack.background": "#21252b",
                        "debugVariables.infoForeground": "#61afef",
                        "debugVariables.warningForeground": "#e5c07b",
                        "debugVariables.errorForeground": "#e06c75",
                        "debugVariables.foreground": "#abb2bf",
                        "debugVariables.background": "#21252b",
                        "debugWatch.infoForeground": "#61afef",
                        "debugWatch.warningForeground": "#e5c07b",
                        "debugWatch.errorForeground": "#e06c75",
                        "debugWatch.foreground": "#abb2bf",
                        "debugWatch.background": "#21252b",
                        "debugConsoleInput.border": "#3e4451",
                        "debugConsoleInput.foreground": "#abb2bf",
                        "debugConsoleInput.background": "#282c34",
                        "debugConsole.sourceForeground": "#abb2bf",
                        "debugConsole.infoForeground": "#61afef",
                        "debugConsole.warningForeground": "#e5c07b",
                        "debugConsole.errorForeground": "#e06c75",
                        "debugConsole.foreground": "#abb2bf",
                        "debugConsole.background": "#21252b",
                        "debugToolBar.border": "#3e4451",
                        "debugToolBar.foreground": "#abb2bf",
                        "debugToolBar.background": "#282c34",
                        "walkThrough.embeddedEditorBorder": "#3e4451",
                        "walkThrough.embeddedEditorBackground": "#282c34",
                        "extensionIcon.lockedForeground": "#5c6370",
                        "extensionIcon.starForeground": "#e5c07b",
                        "extensionButton.secondaryHoverBackground": "#5c6370",
                        "extensionButton.secondaryForeground": "#abb2bf",
                        "extensionButton.secondaryBackground": "#3e4451",
                        "extensionButton.prominentHoverBackground": "#61afef",
                        "extensionButton.prominentForeground": "#ffffff",
                        "extensionButton.prominentBackground": "#528bff",
                        "welcomePage.separatorForeground": "#3e4451",
                        "welcomePage.headerForeground": "#abb2bf",
                        "welcomePage.headerBackground": "#282c34",
                        "welcomePage.tileBorder": "#3e4451",
                        "welcomePage.tileForeground": "#abb2bf",
                        "welcomePage.tileHoverBackground": "#5c6370",
                        "welcomePage.tileBackground": "#3e4451",
                        "welcomePage.buttonForeground": "#abb2bf",
                        "welcomePage.buttonHoverBackground": "#5c6370",
                        "welcomePage.buttonBackground": "#3e4451",
                        "welcomePage.foreground": "#abb2bf",
                        "welcomePage.background": "#282c34",
                        "scm.diffRemovedTextBackground": "#3e4451",
                        "scm.diffInsertedTextBackground": "#3e4451",
                        "scm.diffRemovedLineBackground": "#3e4451",
                        "scm.diffInsertedLineBackground": "#3e4451",
                        "scm.inputBorder": "#3e4451",
                        "scm.inputForeground": "#abb2bf",
                        "scm.inputBackground": "#3e4451",
                        "scm.resourceConflictedForeground": "#e06c75",
                        "scm.resourceIgnoredForeground": "#5c6370",
                        "scm.resourceUntrackedForeground": "#abb2bf",
                        "scm.resourceCopiedForeground": "#61afef",
                        "scm.resourceRenamedForeground": "#61afef",
                        "scm.resourceAddedForeground": "#98c379",
                        "scm.resourceModifiedForeground": "#e5c07b",
                        "scm.resourceDeletedForeground": "#e06c75",
                        "scm.resourceForeground": "#abb2bf",
                        "scm.changeAddedForeground": "#98c379",
                        "scm.changeModifiedForeground": "#e5c07b",
                        "scm.changeDeletedForeground": "#e06c75",
                        "scm.changeForeground": "#abb2bf",
                        "scm.headerForeground": "#abb2bf",
                        "scm.headerBackground": "#21252b",
                        "scm.providerBorder": "#3e4451",
                        "gitDecoration.submoduleResourceForeground": "#61afef",
                        "gitDecoration.conflictingResourceForeground": "#e06c75",
                        "gitDecoration.ignoredResourceForeground": "#5c6370",
                        "gitDecoration.untrackedResourceForeground": "#abb2bf",
                        "gitDecoration.addedResourceForeground": "#98c379",
                        "gitDecoration.deletedResourceForeground": "#e06c75",
                        "gitDecoration.modifiedResourceForeground": "#e5c07b",
                        "mergeEditor.toolbarButtonPressedBorder": "#5c6370",
                        "mergeEditor.toolbarButtonPressedForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonPressedBackground": "#5c6370",
                        "mergeEditor.toolbarButtonHoverBorder": "#5c6370",
                        "mergeEditor.toolbarButtonHoverForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonHoverBackground": "#5c6370",
                        "mergeEditor.toolbarButtonBorder": "#3e4451",
                        "mergeEditor.toolbarButtonForeground": "#abb2bf",
                        "mergeEditor.toolbarButtonBackground": "#3e4451",
                        "mergeEditor.toolbarBorder": "#3e4451",
                        "mergeEditor.toolbarForeground": "#abb2bf",
                        "mergeEditor.toolbarBackground": "#21252b",
                        "mergeEditor.inlineButtonPressedBorder": "#5c6370",
                        "mergeEditor.inlineButtonPressedForeground": "#abb2bf",
                        "mergeEditor.inlineButtonPressedBackground": "#5c6370",
                        "mergeEditor.inlineButtonHoverBorder": "#5c6370",
                        "mergeEditor.inlineButtonHoverForeground": "#abb2bf",
                        "mergeEditor.inlineButtonHoverBackground": "#5c6370",
                        "mergeEditor.inlineButtonBorder": "#3e4451",
                        "mergeEditor.inlineButtonForeground": "#abb2bf",
                        "mergeEditor.inlineButtonBackground": "#3e4451",
                        "mergeEditor.removedTextBackground": "#3e4451",
                        "mergeEditor.insertedTextBackground": "#3e4451",
                        "mergeEditor.removedLineBackground": "#3e4451",
                        "mergeEditor.insertedLineBackground": "#3e4451",
                        "mergeEditor.hoverBorder": "#5c6370",
                        "mergeEditor.hoverBackground": "#3e4451",
                        "mergeEditor.resultHeaderForeground": "#abb2bf",
                        "mergeEditor.resultHeaderBackground": "#21252b",
                        "mergeEditor.commonHeaderForeground": "#abb2bf",
                        "mergeEditor.commonHeaderBackground": "#21252b",
                        "mergeEditor.incomingHeaderForeground": "#abb2bf",
                        "mergeEditor.incomingHeaderBackground": "#21252b",
                        "mergeEditor.currentHeaderForeground": "#abb2bf",
                        "mergeEditor.currentHeaderBackground": "#21252b",
                        "mergeEditor.conflictBorder": "#5c6370",
                        "mergeEditor.conflictBackground": "#3e4451",
                        "mergeEditor.outputHeaderForeground": "#abb2bf",
                        "mergeEditor.outputHeaderBackground": "#21252b",
                        "mergeEditor.outputBorder": "#3e4451",
                        "mergeEditor.outputBackground": "#282c34",
                        "mergeEditor.inputHeaderForeground": "#abb2bf",
                        "mergeEditor.inputHeaderBackground": "#21252b",
                        "mergeEditor.inputBorder": "#3e4451",
                        "mergeEditor.inputBackground": "#282c34",
                        "mergeEditor.headerForeground": "#abb2bf",
                        "mergeEditor.headerBackground": "#21252b",
                        "mergeEditor.border": "#3e4451",
                        "mergeEditor.background": "#282c34",
                        "notebookOutline.sectionHeaderBorder": "#3e4451",
                        "notebookOutline.sectionHeaderForeground": "#abb2bf",
                        "notebookOutline.rowBorder": "#3e4451",
                        "notebookOutline.selectedRowForeground": "#abb2bf",
                        "notebookOutline.selectedRowBackground": "#3e4451",
                        "notebookOutline.hoverRowBackground": "#3e4451",
                        "notebookOutline.focusedRowBackground": "#3e4451",
                        "notebookOutline.border": "#3e4451",
                        "notebookOutline.foreground": "#abb2bf",
                        "notebookOutline.background": "#21252b",
                        "notebookHeaderCell.selectedBorder": "#3e4451",
                        "notebookHeaderCell.selectedBackground": "#3e4451",
                        "notebookHeaderCell.hoverBorder": "#3e4451",
                        "notebookHeaderCell.hoverBackground": "#3e4451",
                        "notebookHeaderCell.border": "#3e4451",
                        "notebookHeaderCell.foreground": "#abb2bf",
                        "notebookHeaderCell.background": "#21252b",
                        "notebookHeader.border": "#3e4451",
                        "notebookHeader.foreground": "#abb2bf",
                        "notebookHeader.background": "#21252b",
                        notebookToolbarSeparator: "#3e4451",
                        "notebookToolbarButton.hoverBorder": "#3e4451",
                        "notebookToolbarButton.hoverBackground": "#3e4451",
                        "notebookToolbar.border": "#3e4451",
                        "notebookToolbar.foreground": "#abb2bf",
                        "notebookToolbar.background": "#21252b",
                        "notebook.outputItemHoverBackgroundColor": "#3e4451",
                        "notebook.outputItemBorderColor": "#3e4451",
                        "notebook.outputItemBackgroundColor": "#21252b",
                        "notebook.outputContainerHoverBackgroundColor": "#3e4451",
                        "notebook.outputContainerBorderColor": "#3e4451",
                        "notebook.outputContainerBackgroundColor": "#21252b",
                        "notebook.scrollbarSlider.activeBackground": "#5c6370",
                        "notebook.scrollbarSlider.hoverBackground": "#5c6370",
                        "notebook.scrollbarSlider.background": "#3e4451",
                        "notebook.symbolHighlightBackground": "#3e4451",
                        "notebook.selectedCellBorder": "#5c6370",
                        "notebook.selectedCellBackground": "#3e4451",
                        "notebook.insertionCellBackground": "#3e4451",
                        "notebook.inactiveSelectedCellBackground": "#3e4451",
                        "notebook.focusedCellBorder": "#5c6370",
                        "notebook.focusedCellBackground": "#3e4451",
                        "notebook.editorForeground": "#abb2bf",
                        "notebook.editorBackground": "#282c34",
                        "notebook.cellToolbarSeparator": "#3e4451",
                        "notebook.cellStatusBarItemHoverBackground": "#3e4451",
                        "notebook.cellInsertionIndicator": "#528bff",
                        "notebook.cellHoverBackground": "#3e4451",
                        "notebook.cellBorderColor": "#3e4451",
                        "breadcrumbseparator.foreground": "#5c6370",
                        "breadcrumb.inactiveSelectionForeground": "#abb2bf",
                        "breadcrumb.activeSelectionForeground": "#528bff",
                        "breadcrumb.focusForeground": "#528bff",
                        "breadcrumb.foreground": "#abb2bf",
                        "breadcrumb.background": "#282c34",
                    },
                });
                // @ts-ignore
                editor = monaco.editor.create(editorContainer.value, {
                    value: defaultCode,
                    language: "ruby",
                    theme: "one-dark-pro",
                    minimap: { enabled: true },
                    automaticLayout: true,
                });
            });
        };
        document.head.appendChild(script);
    }
});

onUnmounted(() => {
    if (editor) {
        editor.dispose();
    }
});
</script>

<style scoped>
.ruby-playground {
  width: 100%;
  max-width: 1000px;
  margin: 0 auto;
  padding: 20px;
  background-color: #f5f5f5;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.ruby-playground h2 {
  text-align: center;
  margin-bottom: 20px;
  color: #333;
}

.playground-container {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.code-editor {
  width: 100%;
}

.editor-container {
  width: 100%;
  min-height: 300px;
  border-radius: 4px;
  overflow: hidden;
}

.playground-controls {
  display: flex;
  gap: 10px;
}

.run-button, .reset-button {
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: bold;
}

.run-button {
  background-color: #4CAF50;
  color: white;
}

.run-button:hover {
  background-color: #45a049;
}

.reset-button {
  background-color: #f44336;
  color: white;
}

.reset-button:hover {
  background-color: #da190b;
}

.output-container {
  width: 100%;
  background-color: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 15px;
}

.output-container h3 {
  margin-top: 0;
  margin-bottom: 10px;
  color: #333;
}

.output {
  font-family: 'Courier New', Courier, monospace;
  font-size: 14px;
  white-space: pre-wrap;
  line-height: 1.5;
}
</style>
